In [23]:
import numpy as np
st_att=np.random.rand(10)
print("\n->10 random values between 0 and 1:\n",st_att)
present=st_att>0.5
absent=st_att<=0.5
print("\n->Present values using Boolean indexing:",st_att[present])
scores=np.random.randint(0,100,15)
print("Scores:",scores)
print("\n->Scores greater than 60:",scores[scores>60])
print("\n->Scores  divisible by 5:",scores[scores%5==0])
arr=np.array( [100, 200, 300, 400, 500])
indices=[0,2,4]
print("\n->1st, 3rd and 5th elements using fancy indexing:",arr[indices])
arr_int=np.random.randint(1,50,(4,4))
print("\n->4x4 matrix:\n",arr_int)
print("\n->Entire 2nd row:",arr_int[1,:])
print("\n->Entire 3rd column:",arr_int[:,2])
uniform_vals = np.random.uniform(0, 1, size=5)
normal_vals = np.random.normal(0, 1, size=5)
print("->\n5 values using np.random.uniform(0, 1):",uniform_vals)
print("->\n5 values using np.random.normal(0, 1):",normal_vals)


->10 random values between 0 and 1:
 [0.99567599 0.59083703 0.24373432 0.30175069 0.56376846 0.57629686
 0.72807134 0.04112104 0.53352135 0.22898841]

->Present values using Boolean indexing: [0.99567599 0.59083703 0.56376846 0.57629686 0.72807134 0.53352135]
Scores: [ 0 43  9 65 98 36 33 28  0 83 42 84 50 67 24]

->Scores greater than 60: [65 98 83 84 67]

->Scores  divisible by 5: [ 0 65  0 50]

->1st, 3rd and 5th elements using fancy indexing: [100 300 500]

->4x4 matrix:
 [[29 20 24 15]
 [ 9 18 18 11]
 [40 15 37 30]
 [ 9 15  7 27]]

->Entire 2nd row: [ 9 18 18 11]

->Entire 3rd column: [24 18 37  7]
->
5 values using np.random.uniform(0, 1): [0.13929207 0.84628045 0.48155656 0.91903097 0.93788725]
->
5 values using np.random.normal(0, 1): [ 0.22675899 -0.35162881 -0.8335515  -0.91047619  0.04997927]
