In [6]:
import numpy as np
arr1D = np.array([60, 70, 80, 90, 100])
arr2D = np.array([[56,89,90], [45,57,78]])
arr3D =arr_3d = np.array([[[60, 70, 80],[75, 85, 95]],[[65, 75, 85],[80, 90, 100]]])
print("->Array 1:\n",arr1D)
print("\n->Array 2:\n",arr2D)
print("\n->Array 3:\n",arr3D)
print("\n->Array shape:",arr2D.shape)
print("\n->Array dimension:",arr2D.ndim)
print("\n->Array dtype:",arr2D.dtype)
print("\n->Array size:",arr2D.size)
arr0 = np.zeros((3,4))
print("\n->Array filled with 0:\n",arr0)
arr1= np.ones((2,3))
print("\n->Array filled with 1:\n",arr1)
arrfull= np.full((3,3), 5)
print("\n->Array filled with value 5:\n",arrfull)
arr_ls= np.arange(10, 50, 10)
print("\n->Array from 10 to 50 with step 10:\n",arr_ls)
arr_ls= np.linspace(0,100,5)
print("\n->A 5 evenly spaced values between 0 and 100:\n",arr_ls)
arr_eye= np.eye(4)
print("\n->4×4 identity matrix:\n",arr_eye)
arr_dl= np.diag([10,20,30,40])
print("\n->diagonal matrix with values [10, 20, 30, 40]:\n",arr_dl)

->Array 1:
 [ 60  70  80  90 100]

->Array 2:
 [[56 89 90]
 [45 57 78]]

->Array 3:
 [[[ 60  70  80]
  [ 75  85  95]]

 [[ 65  75  85]
  [ 80  90 100]]]

->Array shape: (2, 3)

->Array dimension: 2

->Array dtype: int64

->Array size: 6

->Array filled with 0:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

->Array filled with 1:
 [[1. 1. 1.]
 [1. 1. 1.]]

->Array filled with value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

->Array from 10 to 50 with step 10:
 [10 20 30 40]

->A 5 evenly spaced values between 0 and 100:
 [  0.  25.  50.  75. 100.]

->4×4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

->diagonal matrix with values [10, 20, 30, 40]:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
