In [6]:
import numpy as np
marks_term1=np.array([60, 70, 80, 90])
marks_term2=np.array([65, 75, 85, 95])
total_marks=np.array(marks_term1+marks_term2)
print("\n->Total marks:",total_marks)
print("\n->Difference:",marks_term1-marks_term2)
print("\n->Increase percentage using multiplication by 1.05:\n",marks_term1*1.05,"\n",marks_term2*1.05)
greater=total_marks>150
print("\n->Marks greater than 150:",total_marks[greater])
btwn=(total_marks>140) & (total_marks<170)
print("\n->Marks between 140 and 170:",total_marks[btwn])
print("\n->Sum of total marks:",total_marks.sum())
print("\n->Mean of total marks:",total_marks.mean())
print("\n->Maximum of total marks:",total_marks.max())
print("\n->Minimum of total marks:",total_marks.min())
print("\n->Standard deviation of total marks:",total_marks.std())
marks=np.array([[70, 80, 90],[60, 75, 85]])
print("\n->Marks:\n",marks)
print("\n->Column-wise sum of marks:",marks.sum(axis=0))
print("\n->Row-wise mean of marks:",marks.mean(axis=1))
arr1D=np.array([1, 2, 3, 4, 5, 6])
print("\n->Array shape:",arr1D.shape)
print("\n->Array dimension:",arr1D.ndim)
print("\n->Array dtype:",arr1D.dtype)
print("\n->Array size:",arr1D.size)
reshaped = arr1D.reshape((2, 3))
print("\n->Reshaped:\n",reshaped)
print("\n->Convert it back to 1D using ravel():",reshaped.ravel())



->Total marks: [125 145 165 185]

->Difference: [-5 -5 -5 -5]

->Increase percentage using multiplication by 1.05:
 [63.  73.5 84.  94.5] 
 [68.25 78.75 89.25 99.75]

->Marks greater than 150: [165 185]

->Marks between 140 and 170: [145 165]

->Sum of total marks: 620

->Mean of total marks: 155.0

->Maximum of total marks: 185

->Minimum of total marks: 125

->Standard deviation of total marks: 22.360679774997898

->Marks:
 [[70 80 90]
 [60 75 85]]

->Column-wise sum of marks: [130 155 175]

->Row-wise mean of marks: [80.         73.33333333]

->Array shape: (6,)

->Array dimension: 1

->Array dtype: int64

->Array size: 6

->Reshaped:
 [[1 2 3]
 [4 5 6]]

->Convert it back to 1D using ravel(): [1 2 3 4 5 6]
