In [1]:
import numpy as np
student_ids = np.arange(101, 121)
print("\n->Student ID:", student_ids)
print("\n->Shape of array:", student_ids.shape)
print("\n->Size of array:", student_ids.size)
print("\n->Datatype of array:", student_ids.dtype)
attendance = np.ones((5, 5))
attendance[1, 2] = 0
attendance[3, 4] = 0
print("\n->Attendance details:\n",attendance)
print("\n->Number od dimensions:",attendance.ndim)
scores = np.zeros((4, 3))
print("\n->Initial score board:\n", scores)
grading_scale = np.linspace(0, 100, 6)
print("\n->Grading scale:",grading_scale)
identity_matrix = np.eye(5)
diagonal_matrix = np.diag([2, 4, 6, 8, 10])
print("\n->Identity Matrix:\n", identity_matrix)
diagonal_matrix = np.diag([2, 4, 6, 8, 10])
print("\n->diagonal Matrix:\n", diagonal_matrix)


->Student ID: [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120]

->Shape of array: (20,)

->Size of array: 20

->Datatype of array: int64

->Attendance details:
 [[1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]

->Number od dimensions: 2

->Initial score board:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

->Grading scale: [  0.  20.  40.  60.  80. 100.]

->Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

->diagonal Matrix:
 [[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]
