In [4]:
import numpy as np
daily_sales=np.array([250.75, 300.40, 275.60, 400.90, 150.30, 500.50, 350.80])
print("Daily sales Analysis\n")
print("->Total sales:",(np.sum(daily_sales)))
print("->Average sales:",(np.mean(daily_sales)))
print("->Median sales:",(np.median(daily_sales)))
print("->Sales variation:",(np.std(daily_sales)))
print("->Minimum sale:",(np.min(daily_sales)))
print("->Maximum sale:",(np.max(daily_sales)))
print("->floor() to sales:",np.floor(daily_sales))
print("->ceil() to sales:",np.ceil(daily_sales))
print("->round() to sales:",np.round(daily_sales))
print("->Exponential growth:",np.exp(daily_sales))
print("->Cumulative sales:",np.cumsum(daily_sales))
A=np.array([[2, 1],[3, 4]])
B= np.array([[1, 2],[5, 6]])
print("\nMatrix Operations:\n")
print("A=\n",A)
print("B=\n",B)
print("->Matrix multiplication:\n",A@B)
print("->Determinant of matrix A:",np.linalg.det(A))
print("->Inverse of matrix A:\n",np.linalg.inv(A))
values, vectors = np.linalg.eig(A)
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)
a=np.array([[2,1],[3,4]])
b=np.array([5,11])
x = np.linalg.solve(a, b)
print("->Linear equation solution:",x)

Daily sales Analysis

->Total sales: 2229.25
->Average sales: 318.4642857142857
->Median sales: 300.4
->Sales variation: 104.2019766548385
->Minimum sale: 150.3
->Maximum sale: 500.5
->floor() to sales: [250. 300. 275. 400. 150. 500. 350.]
->ceil() to sales: [251. 301. 276. 401. 151. 501. 351.]
->round() to sales: [251. 300. 276. 401. 150. 500. 351.]
->Exponential growth: [7.93124448e+108 2.89775967e+130 4.91540393e+119 1.28427431e+174
 1.88131115e+065 2.31413234e+217 2.24132199e+152]
->Cumulative sales: [ 250.75  551.15  826.75 1227.65 1377.95 1878.45 2229.25]

Matrix Operations:

A=
 [[2 1]
 [3 4]]
B=
 [[1 2]
 [5 6]]
->Matrix multiplication:
 [[ 7 10]
 [23 30]]
->Determinant of matrix A: 5.000000000000001
->Inverse of matrix A:
 [[ 0.8 -0.2]
 [-0.6  0.4]]
Eigenvalues: [1. 5.]
Eigenvectors:
 [[-0.70710678 -0.31622777]
 [ 0.70710678 -0.9486833 ]]
->Linear equation solution: [1.8 1.4]
