In [23]:
import numpy as np
arr_rand=np.random.rand(5)
arr_randn=np.random.randn(5)
print("->Random values representing normalized scores:",arr_rand)
print("\n->Random values from a normal distribution:",arr_randn)
arr_int=np.random.randint(35, 100, (3,4))
print("\n->3×4 array of random integers between 35 and 100:\n",arr_int)
student_IDs=np.array([101, 102, 103, 104, 105])
print("\n->Randomly select 2 students:",np.random.choice(student_IDs, size=2))
np.random.seed(10)
print("\n->Generate 3 random values using seed:",np.random.choice(student_IDs, size=3))
arr=np.array([10, 20, 30, 40, 50, 60])
print("\n->3rd element:",arr[2])
print("\n->Elements from index 1 to 4:",arr[1:5])
print("\n->Last element:",arr[-1])
print("\n->Every second element:",arr[1::2])
print("\n->Reversed array:",arr[::-1])


->Random values representing normalized scores: [0.44301495 0.83191136 0.58332174 0.02517173 0.70920801]

->Random values from a normal distribution: [-0.90561048 -0.89808938  0.45187984 -0.85947418 -0.53479453]

->3×4 array of random integers between 35 and 100:
 [[97 68 84 86]
 [89 48 60 48]
 [65 65 47 66]]

->Randomly select 2 students: [102 105]

->Generate 3 random values using seed: [102 105 101]

->3rd element: 30

->Elements from index 1 to 4: [20 30 40 50]

->Last element: 60

->Every second element: [20 40 60]

->Reversed array: [60 50 40 30 20 10]
