In [10]:
import numpy as np
m_sales=np.array([100, 120, 130, 150, 170, 160, 180, 200, 210, 190, 220, 250])
reshaped=m_sales.reshape((3,4))
print("->Reshaped:\n",reshaped)
print("\n->Convert it back to 1D using ravel():",reshaped.ravel())
print("\n->Convert it back to 1D using flatten():",reshaped.flatten())
dept1=np.array([100, 200, 300])
dept2 =np.array([400, 500, 600])
print("\n->Combined using hstack:",np.hstack((dept1,dept2)))
print("\n->Combined using vstack:",np.vstack((dept1,dept2)))
a = [[1, 2]]
b = [[3, 4]]
print("\n->Concatenated Row-wise:",np.concatenate((a, b), axis=0))
print("\n->Concatenated Column-wise:",np.concatenate((a, b), axis=1))
arr1D=np.array( [10, 20, 30, 40, 50, 60])
arr2D=np.array([[1, 2,0], [3, 4,0], [5, 6,0]])
print("\n->Split it into 3 equal parts:",np.split(arr2D,3))
print("\n->Split columns using hsplit:",np.hsplit(arr2D, 3))
print("\n->Split columns using vsplit:",np.vsplit(arr2D, 3))

->Reshaped:
 [[100 120 130 150]
 [170 160 180 200]
 [210 190 220 250]]

->Convert it back to 1D using ravel(): [100 120 130 150 170 160 180 200 210 190 220 250]

->Convert it back to 1D using flatten(): [100 120 130 150 170 160 180 200 210 190 220 250]

->Combined using hstack: [100 200 300 400 500 600]

->Combined using vstack: [[100 200 300]
 [400 500 600]]

->Concatenated Row-wise: [[1 2]
 [3 4]]

->Concatenated Column-wise: [[1 2 3 4]]

->Split it into 3 equal parts: [array([[1, 2, 0]]), array([[3, 4, 0]]), array([[5, 6, 0]])]

->Split columns using hsplit: [array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([[0],
       [0],
       [0]])]

->Split columns using vsplit: [array([[1, 2, 0]]), array([[3, 4, 0]]), array([[5, 6, 0]])]
